version: "3.0"

expectations:
  population_size: 1000

actions:
  query:
    run: >
      sqlrunner:latest
        --dummy-data-file output/generate_dummy_rows/dummy_rows.csv.gz
        --output output/query/rows.csv.gz
        analysis/query.sql
    outputs:
      highly_sensitive:
        rows: output/query/rows.csv.gz

  latest_import_dates:
    needs: [query]
    run: python:latest python -m analysis.latest_import_dates
    outputs:
      moderately_sensitive:
        latest_import_dates: output/latest_import_dates/latest_import_dates.csv

  plot:
    needs: [query]
    run: python:latest python -m analysis.plot
    outputs:
      moderately_sensitive:
        latest_import_dates: output/plot/plot.png

  render_report:
    needs: [latest_import_dates, plot]
    run: python:latest python -m analysis.render_report
    outputs:
      moderately_sensitive:
        report: output/render_report/report.html
