[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories
    | \.direnv
    | \.github
    | \.pytest_cache
    | \.venv
    | htmlcov
    | venv
  )/
)
'''

[tool.sqlfluff.core]
dialect = "tsql"
exclude_rules = "CP02"
